### ISSUE TITLE
CodeIgniter :-)

### ISSUE THREAD

**Issue by ivantcholakov** [T1st3/vendor-icons#1]
https://codeigniter.com
https://github.com/bcit-ci/codeigniter-website/tree/develop/assets/images
If you need more information probably @jim-parry would help.

**Comment by jim-parry** [comment]
The CodeIgniter icons are ok to include, the BCIT ones not.

**Comment by t1st3** [comment]
Just added an icon for CodeIgniter, and bumped the project to 0.4.0.
Thanks for the suggestion

**Comment by t1st3** [comment]
Closing for now. Please comment or re-open if the icon is not what you expected.

**Comment by ivantcholakov** [comment]
Thank you.
